# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
                ('instructions', models.CharField(max_length=2048)),
                ('is_private', models.BooleanField()),
            ],
        ),
    ]
