# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammapping',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammapping',
            name='sequence_number',
            field=models.IntegerField(),
        ),
    ]
