# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='searchfoodgroup',
            old_name='search_id',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='searchtag',
            old_name='search_id',
            new_name='search',
        ),
        migrations.RenameField(
            model_name='searchtag',
            old_name='tag_name',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='foodgroup',
            name='food_group_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='search_id',
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
