# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20161204_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='food_group_id',
            new_name='food_group',
        ),
    ]
