# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20161204_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='searchfoodgroup',
            old_name='food_group_id',
            new_name='food_group',
        ),
    ]
