# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0003_auto_20161207_0239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=set([('user', 'recipe')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersubmission',
            unique_together=set([('user', 'recipe')]),
        ),
    ]
