# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20161204_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food_group_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='parent_recipe_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
    ]
