# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20161207_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='ingredient_search_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='recipe_search_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
