# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20161205_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cookbook.Tag'),
        ),
    ]
