# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20161205_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurements',
        ),
        migrations.AddField(
            model_name='grammapping',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Ingredient'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grammapping',
            unique_together=set([('ingredient', 'sequence_number')]),
        ),
    ]
