# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_auto_20161205_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
