# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='TestRecipe',
        ),
    ]
